### ISSUE TITLE
Cannot find module '@sailshq/lodash'

### ISSUE THREAD

**Issue by iyogeshjoshi** [erikschlegel/sails-generate-reactjs#16]
After following each step for installation when I try to run `sails lift` it gives me following error I tried installing that module separately but the error is not going.

```bash
$ sails lift
module.js:472
    throw err;
    ^

Error: Cannot find module '@sailshq/lodash'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/sails/bin/sails.js:8:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by ChunckNorris** [comment]
Has this issue had a response yet?

**Comment by uncooloj** [comment]
Please has this issue had a response yet??

**Comment by lucky-mishra** [comment]
I am having the same problem

**Comment by iyogeshjoshi** [comment]
Well uninstalling old `sails` and installing again and then creating a new project worked for me. Try running the following commands:
```bash
# might need sudo rights for this
$ npm un -g sails
$ npm i -g sails

# Create new project
# $ cd <to/some/new/directory>
$ sails new sails-new-project
$ sails lift
```

**Comment by ali-pourzahmatkesh** [comment]
same  problem !

**Comment by fpjhannan** [comment]
Check out this thread; it helped me: https://stackoverflow.com/questions/27431187/cannot-find-module-lodash

**Comment by IwonaGorska** [comment]
Run npm install in project folder.

![obraz](https://user-images.githubusercontent.com/39538610/83924248-76ddf200-a784-11ea-852f-404a878856ba.png)
