### ISSUE TITLE
 Failed to load "sails-generate-reactjs"

### ISSUE THREAD

**Issue by mtbvang** [erikschlegel/sails-generate-reactjs#4]
I'm following the instructions in the README and am getting the following error when I run 

`sails new <app name> --force`

Looks like sails is only looking for the module locally. How do I get it to look globally for it? The module is installed globally in /usr/local/lib/node_modules/sails-generate-reactjs.

error: Error: Generator Error: Failed to load "sails-generate-reactjs"... (Error: Cannot find module '/vagrant/node_modules/sails-generate-reactjs')
    at parseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:264:7)
    at tryToParseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:44:7)
    at Object.async.until (/usr/local/lib/node_modules/sails/node_modules/sails-generate/node_modules/async/lib/async.js:647:13)
    at /usr/local/lib/node_modules/sails/node_modules/sails-generate/node_modules/async/lib/async.js:651:23
    at /usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:47:16
    at parseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:192:16)
    at tryToParseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:44:7)
    at Object.async.until (/usr/local/lib/node_modules/sails/node_modules/sails-generate/node_modules/async/lib/async.js:647:13)
    at generateTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:39:9)
    at /usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/generate.js:143:15 [Error: Generator Error: Failed to load "sails-generate-reactjs"... (Error: Cannot find module '/vagrant/node_modules/sails-generate-reactjs')]

**Comment by colus001** [comment]
@mtbvang Did you fix this error? I'm having same error like this.

```
error: Error: Generator Error: Failed to load "sails-generate-reactjs"... (Error: Cannot find module '/Users/KimSeokjun/Development/node_modules/sails-generate-reactjs')
    at parseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:264:7)
    at tryToParseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:44:7)
    at Object.async.until (/usr/local/lib/node_modules/sails/node_modules/sails-generate/node_modules/async/lib/async.js:647:13)
    at /usr/local/lib/node_modules/sails/node_modules/sails-generate/node_modules/async/lib/async.js:651:23
    at /usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:47:16
    at parseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:192:16)
    at tryToParseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:44:7)
    at Object.async.until (/usr/local/lib/node_modules/sails/node_modules/sails-generate/node_modules/async/lib/async.js:647:13)
    at generateTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:39:9)
    at /usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/generate.js:143:15 [Error: Generator Error: Failed to load "sails-generate-reactjs"... (Error: Cannot find module '/Users/KimSeokjun/Development/node_modules/sails-generate-reactjs')]
```

It doesn't look for global modules.

**Comment by RSilverFitzmall** [comment]
Has anyone figured this out?

**Comment by addisonwoods** [comment]
Has anyone figure this out?

**Comment by appjitsu** [comment]
having the same issue...

**Comment by strataga** [comment]
reopened: https://github.com/erikschlegel/sails-generate-reactjs/issues/8
